[project]
name = "mantis"
version = "0.1.0"
description = "Serveur MCP pour Mantis"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.3",
    "requests>=2.32.3",
]
